const ADDITION = 'ADDITION/addition';
const ADDITION_FAILED = 'ADDITION_FAILED/addition';
const ADD_ADDITION = 'ADD_ADDITION/addition';
const DELETE_ADDITION = 'DELETE_ADDITION/addition';
const ADDITION_SUCCESS = 'ADDITION_SUCCESS/addition';
const SELECT_ADDITION = 'SELECT_ADDITION/addition';
const UNSELECT_ADDITION = 'UNSELECT_ADDITION/addition';
const SET_ADDITION = 'SET_ADDITION/addition';
export default {
  ADDITION,
  ADDITION_SUCCESS,
  ADDITION_FAILED,
  DELETE_ADDITION,
  ADD_ADDITION,
  SELECT_ADDITION,
  UNSELECT_ADDITION,
  SET_ADDITION,
};
