const ADDITION = 'ADDITION/addition';
const ADDITION_FAILED = 'ADDITION_FAILED/addition';
const ADD_ADDITION = 'ADD_ADDITION/addition';
const DELETE_ADDITION = 'DELETE_ADDITION/addition';
const ADDITION_SUCCESS = 'ADDITION_SUCCESS/addition';
export default {
  ADDITION,
  ADDITION_SUCCESS,
  ADDITION_FAILED,
  DELETE_ADDITION,
  ADD_ADDITION,
};
