const GET_USERS = 'GET_USERS/users';
const GET_USERS_FAILED = 'GET_USERS_FAILED/users';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS/users';

export default {GET_USERS, GET_USERS_SUCCESS, GET_USERS_FAILED};
