const TRANSLATE = 'TRANSLATE/translate';
const TRANSLATE_FAILED = 'TRANSLATE_FAILED/translate';
const TRANSLATE_SUCCESS = 'TRANSLATE_SUCCESS/translate';
export default {TRANSLATE, TRANSLATE_SUCCESS, TRANSLATE_FAILED};
