const pinCode = 'pinCode/pinCode';
const pinCode_FAILED = 'pinCode_FAILED/pinCode';
const pinCode_SUCCESS = 'pinCode_SUCCESS/pinCode';
const GET_MENU = 'GET_MENU/pinCode';
const GET_MENU_FAILED = 'GET_MENU_FAILED/pinCode';
const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS/pinCode';
const GET_PRODUCT_PORTION = 'GET_PRODUCT_PORTION/pinCode';
const GET_PRODUCT_PORTION_FAILED = 'GET_PRODUCT_PORTION_FAILED/pinCode';
const GET_PRODUCT_PORTION_SUCCESS = 'GET_PRODUCT_PORTION_SUCCESS/pinCode';
export default {
  pinCode,
  pinCode_SUCCESS,
  pinCode_FAILED,
  GET_MENU,
  GET_MENU_FAILED,
  GET_MENU_SUCCESS,
  GET_PRODUCT_PORTION,
  GET_PRODUCT_PORTION_FAILED,
  GET_PRODUCT_PORTION_SUCCESS,
};
