const GET_MENU = 'GET_MENU/pinCode';
const GET_MENU_FAILED = 'GET_MENU_FAILED/pinCode';
const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS/pinCode';
const GET_PRODUCT_PORTION = 'GET_PRODUCT_PORTION/pinCode';
const GET_PRODUCT_PORTION_FAILED = 'GET_PRODUCT_PORTION_FAILED/pinCode';
const GET_PRODUCT_PORTION_SUCCESS = 'GET_PRODUCT_PORTION_SUCCESS/pinCode';
const GET_ORDER_TAG = 'GET_ORDER_TAG/pinCode';
const GET_ORDER_TAG_FAILED = 'GET_ORDER_TAG_FAILED/pinCode';
const GET_ORDER_TAG_SUCCESS = 'GET_ORDER_TAG_SUCCESS/pinCode';
const CONNECTION_CONTROL = 'CONNECTION_CONTROL/pinCode';
const CONNECTION_CONTROL_FAILED = 'CONNECTION_CONTROL_FAILED/pinCode';
const CONNECTION_CONTROL_SUCCESS = 'CONNECTION_CONTROL_SUCCESS/pinCode';
export default {
  GET_MENU,
  GET_MENU_FAILED,
  GET_MENU_SUCCESS,
  GET_PRODUCT_PORTION,
  GET_PRODUCT_PORTION_FAILED,
  GET_PRODUCT_PORTION_SUCCESS,
  GET_ORDER_TAG,
  GET_ORDER_TAG_FAILED,
  GET_ORDER_TAG_SUCCESS,
  CONNECTION_CONTROL,
  CONNECTION_CONTROL_FAILED,
  CONNECTION_CONTROL_SUCCESS,
};
